protected/models/Chapter.php
<?php
/**
 * @property Book $book
 *
 * @property string $url via getUrl()
 * @property string $ahref via getAhref()
 * @property string deniedWhy via getDeniedWhy()
 * @property string errorsString via getErrorsString()
 */
class Chapter extends CActiveRecord {
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}
	public function tableName() {
		return 'chapters';
	}

	public $id, $book_id, $cdate, $last_tr, $n_verses = 0, $n_vars = 0, $d_vars = 0;
	public $ord, $status, $title;
	public $ac_read, $ac_trread, $ac_gen, $ac_rate, $ac_comment, $ac_tr;

	// Только для редактора
	public $has_override;

	// EXTRACT(EPOCH FROM now() - last_tr)::int as idle_time
	public $idle_time;

	const STATUS_NONE = 0;
	const STATUS_TRANSLATING = 1;
	const STATUS_EDITING = 2;
	const STATUS_READY = 3;

	public function attributeLabels() {
		return array(
			"title" => "Название",
			"ord" => "Порядок",
			"status" => "Статус"
		);
	}

	public function rules() {
		return array(
			array("title", "required", "message" => "Пожалуйста, введите заголовок"),
			array("ord", "numerical", "integerOnly" => true),
			array("status", "in", "range" => array_keys(Yii::app()->params["translation_statuses"])),
			array("ac_read, ac_trread, ac_gen, ac_rate, ac_comment, ac_tr", "filter", "filter" => "trim"),
			array("ac_read, ac_trread, ac_gen, ac_rate, ac_comment, ac_tr", "in", "range" => array("a", "g", "m", "o")),
			array("has_override", "boolean"),
			array("has_override", "rule_has_override"),
		);
	}

	public function rule_has_override() {
		if(!$this->has_override) {
			foreach(array("ac_read", "ac_trread", "ac_gen", "ac_rate", "ac_comment", "ac_tr") as $ac) $this->$ac = null;
		}
	}

	public function relations() {
		$rel = array(
			"book" => array(self::BELONGS_TO, "Book", "book_id"),
		);

		return $rel;
	}

	protected function afterValidate() {
		foreach(array_keys(Yii::app()->params["ac_areas_chap"]) as $ac) {
			if($this->$ac == "") $this->$ac = null;
		}

		// Если нам указали особые права доступа, проверяем, есть ли уже такие в переводе?
		if($this->ac_read . $this->ac_gen . $this->ac_rate . $this->ac_comment . $this->ac_tr != "") {
			$r = Yii::app()->db
				->createCommand("SELECT 1 FROM chapters WHERE book_id = :book_id AND id != :id AND (ac_read || ac_gen || ac_rate || ac_comment || ac_tr != '')")
				->query(array("book_id" => $this->book_id, "id" => $this->id));

			if($r->rowCount > 0) {
				$this->addError("ac_read", "В переводе только одна глава может иметь особые права доступа.");
			}
		}

		parent::afterValidate();
	}

	public function afterSave() {
		parent::afterSave();

		if($this->isNewRecord) {
			$this->book->n_chapters++;
			$this->book->save(false, array("n_chapters"));
		}
	}

	protected function beforeDelete() {
		// groups.n_trs, rating
		Yii::app()->db->createCommand("
			BEGIN;

			WITH effort AS (
				SELECT user_id, COUNT(*) as n, SUM(rating) as r FROM translate WHERE chap_id = :chap_id GROUP BY user_id
			)
			UPDATE groups SET n_trs = n_trs - effort.n, rating = rating - effort.r
			FROM effort WHERE groups.book_id = :book_id AND groups.user_id = effort.user_id;

			WITH effort AS (
				SELECT user_id, COUNT(*) as n, SUM(rating) as r FROM translate WHERE chap_id = :chap_id GROUP BY user_id
			)
			UPDATE users SET n_trs = n_trs - effort.n, rate_t = rate_t - effort.r
			FROM effort WHERE users.id = effort.user_id;

			COMMIT;
		")->execute(array(":chap_id" => $this->id, ":book_id" => $this->book_id));

		return parent::beforeDelete();
	}

	public function afterDelete() {
		parent::afterDelete();

		$this->book->n_chapters--;
		$this->book->n_verses -= $this->n_verses;
		$this->book->n_vars -= $this->n_vars;
		$this->book->d_vars -= $this->d_vars;

		$this->book->save(false, array("n_chapters", "n_verses", "n_vars", "d_vars"));
	}

	/**
	 * Очищает главу, пересчитывает счётчики n_verses, n_vars, d_vars в book и свои счётчики
	 */
	public function clean() {
		if($this->n_verses != 0 || $this->n_vars != 0 || $this->d_vars != 0) {
			$this->book->n_verses -= $this->n_verses;
			$this->book->n_vars -= $this->n_vars;
			$this->book->d_vars -= $this->d_vars;
			$this->book->save(false, array("n_verses", "n_vars", "d_vars"));
		}

		// translate не очистится из-за того, что foreign-ключ на translate.orig_id жутко тормозит при удалении главы
		Yii::app()->db->createCommand("DELETE FROM orig WHERE chap_id = :chap_id")->execute(array(":chap_id" => $this->id));

		$this->n_verses = 0;
		$this->n_vars = 0;
		$this->d_vars = 0;
		$this->save(false, array("n_verses", "n_vars", "d_vars"));
	}

	public function getUrl($area = "") {
		return "/book/{$this->book_id}/{$this->id}" . ($area != "" ? "/{$area}" : "");
	}

	public function getAhref($area = "") {
		return "<a href='" . $this->getUrl($area) . "'>{$this->title}</a>";
	}

	public function getReady() {
		if($this->n_verses == 0) return "&mdash;";
		if($this->d_vars == 0) return "0%";
		if($this->n_verses == $this->d_vars) return "100%";
		return sprintf("%.01f%%", floor($this->d_vars / $this->n_verses * 1000) / 10);
	}

	/**
	 * @param string $what read|trread|gen|rate|comment|tr
	 * @return bool
	 */
	public function can($what) {
		$user = Yii::app()->user;

		// Хозяин может всё
		if($this->book->owner_id == $user->id) return true;

		// Если у главы статус STATUS_READY, то нельзя переводить и рейтинговать
		if($this->status == self::STATUS_READY) {
			if($what == "rate" || $what == "tr") return false;
		}

		// Можно ли генерировать результат с подставлением оригинала вместо непереведённых фрагментов
		if($what == "gen_untr") {
			if($this->book->typ != "A") return true;
			if($this->d_vars / $this->n_verses >= 0.95) return true;
			if($this->book->ac_read != "a" || ($this->ac_read != "" && $this->ac_read != "a")) return true;
			return false;
		}

		$ac = "ac_" . $what;
		if(!$this->$ac) return $this->book->can($what);

		if($this->$ac == "a") {
			// "a" разрешает анонимам только read и gen
			if(Yii::app()->user->isGuest and !($what == "read" || $what == "gen")) return false;
			else return true;
		}

		if($this->$ac == "g") return $this->book->membership->status == GroupMember::MEMBER or $this->book->membership->status == GroupMember::MODERATOR;
		if($this->$ac == "m") return $this->book->membership->status == GroupMember::MODERATOR;
		if($this->$ac == "o") return $this->book->owner_id == $user->id;

		return false;
	}

	public function getHasOverride() {
		return $this->ac_read != "" || $this->ac_gen != "" || $this->ac_rate != "" || $this->ac_comment != "" || $this->ac_tr != "";
	}

	public function idle_time_text() {
		if($this->last_tr == "") return "&mdash;";

		$t = time() - strtotime($this->last_tr);

		if($t < 60) return $this->idle_time . " сек.";
		if($t < 60 * 60) return round($this->idle_time / 60) . " мин.";
		if($t < 60 * 60 * 24) return round($this->idle_time / 3600) . " час.";
		if($t < 60 * 60 * 24 * 30) return round($this->idle_time / 86400) . " дней.";
		if($t < 60 * 60 * 24 * 30 * 12) return round($this->idle_time / 2592000) . " мес.";
		return "> 1 года.";
	}

	/**
	* Пересчитывает n_verses, n_vars, d_vars
	* @todo: чтобы можно было передать значения счётчиков в параметре и сохранить их сразу, а не пересчитывать
	*/
	public function save_counters() {
		if($this->isNewRecord) return false;

		$this->n_verses = Yii::app()->db->createCommand("SELECT COUNT(*) FROM orig WHERE chap_id = :id")->queryScalar(array("id" => $this->id));
		list($this->n_vars, $this->d_vars) = Yii::app()->db->createCommand("SELECT COUNT(*), COUNT(DISTINCT orig_id) FROM translate WHERE chap_id = :id")->queryRow(false, array("id" => $this->id));

		$this->save(false, array("n_verses", "n_vars", "d_vars"));

		return true;
	}

	public function getErrorsString() {
		$t = "";
		foreach($this->getErrors() as $field => $errors) {
			$t .= join("\n", $errors);
		}

		return $t;
	}

	/**
	 * Возвращает текст типа "Это могут делать только члены группы. Чтобы вступить в группу, нужно подать заявку"
	 *
	 * @param string $what - роль
	 * @param bool $tools  - добавлять ли кнопки для подачи заявки или приёма инвайта в группу
	 * @return string
	 */
	public function getWhoCanDoIt($what = "read", $tools = true) {
		$ac = "ac_" . $what;

		if($this->$ac == "") return $this->book->getWhoCanDoIt($what, $tools);

		$msg = "Это " . ($this->$ac == "o" ? "может" : "могут") . " делать " . Yii::app()->params["ac_roles_title"][$this->$ac] . ".";

		if($this->$ac == "g") {
			if($this->book->facecontrol == Book::FC_CONFIRM) {
				$msg .= "Чтобы вступить в группу, нужно подать заявку владельцу ({$this->book->owner->ahref})" . ($this->book->ac_membership == "m" ? " или модераторам" : "") . ".";
				if($tools) $msg .= Yii::app()->controller->renderPartial("//book/_join", array("book" => $this->book), true);
			} elseif($this->book->facecontrol == Book::FC_INVITE) {
				$msg = "Чтобы вступить в группу, нужно получить приглашение от владельца ({$this->book->owner->ahref})" . ($this->book->ac_membership == "m" ? " или модераторов" : "") . ".";
				if($tools && $this->book->user_invited(Yii::app()->user->id)) {
					$msg .= " Кстати, у вас это приглашение есть.<br /><br /><a href='" . $this->book->getUrl("invite_accept") . "' class='act'>Принять</a> | <a href='" . $this->book->getUrl("invite_decline") . "' class='act'>Отказать</a>";
				}
			}
		}

		return $msg;
	}

	public function getDeniedWhy() {
		if($this->can("read")) return "";

		if($this->ac_read == "o") $msg = "Владелец перевода (" . $this->book->owner->ahref . ") закрыл доступ в эту главу для всех.";
		elseif($this->ac_read == "m") $msg = "Эта глава доступна только модераторам этого перевода, которых назначает владелец (" . $this->book->owner->ahref . ").";
		elseif($this->ac_read == "g") {
			if($this->book->facecontrol == Book::FC_CONFIRM) {
				$msg = "Чтобы войти в эту главу перевода, нужно вступить в группу перевода.";
			} elseif($this->book->facecontrol == Book::FC_INVITE) {

protected/views/chapter/edit.php
<?php
	/**
	* @var Chapter $chap
	* @var integer $overridedId - ID главы с особыми правами доступа в этом переводе; 0, если такой нет; -1, если это единственная глава в переводе
	* @var boolean $ajax - если редактор встраивается в другую страницу
	*/
	$this->pageTitle = "Свойства главы {$chap->title} перевода {$chap->book->fullTitle}";
?>
<style type='text/css'>
	#override-table { display:none; }
	#status-msg { display: none; color:#700; margin: 10px 0 0;}
</style>
<script type="text/javascript">
var E = {
	init: function() {
		E.override();
		$("#Chapter_status").change(E.status_change).change();
	},
	status_change: function() {
		if($(this).val() == 3) $("#status-msg").show();
		else $("#status-msg").hide();
		console.log($(this).val());
	},
	rm: function() {
		$("#btn-remove").attr("disabled", true).text("Это может занять несколько минут...").attr("title", "Самое время выпить чаю!");
		if(!confirm("Вы уверены?")) {
			$("#btn-remove").attr("disabled", false).text("Удалить");
			return;
		}

		$("#form-rm").submit();
	},
	override: function() {
		if($("#override-checkbox").is(":checked")) $("#override-table").show();
		else $("#override-table").hide();
	}
};
$(E.init);
</script>

<?php if(!$ajax): ?><h1><?=$post->isNewRecord ? "Создать главу" : "Свойства главы"; ?></h1><?php endif ?>

<form id="form-rm" method="post" action="<?=$chap->getUrl("remove"); ?>"><input type="hidden" name="really" value="1"/></form>

<?php
	/** @var TbActiveForm $form */
	$form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
		"id" => "form-edit",
		"type" => "horizontal",
		"htmlOptions" => array(
			"style" => "margin-bottom:0;",
		),
	));

	echo $form->errorSummary($chap);

	echo $form->textFieldRow($chap, "title", array("class" => "span5"));
?>
<div class="control-group">
	<label class="control-label">Статус</label>
	<div class="controls">
		<?php echo $form->dropDownList($chap, "status", Yii::app()->params["translation_statuses"]); ?>
		<p id="status-msg">Добавление новых версий перевода и рейтингование будет отключено!</p>
	</div>
</div>
<?php if($overridedId == 0 || $overridedId == $chap->id): ?>
<div class="control-group">
	<div class="controls">
		<label class="checkbox">
			<input type="checkbox" name="Chapter[has_override]" value="1" id="override-checkbox" <?=$chap->hasOverride ? "checked" : "" ?> onclick="E.override()" />
			Особые права доступа (можно установить только для одной главы)
		</label>
		<table class="table table-striped table-condensed table-oneline" id="override-table">
		<thead><tr>
			<th>Действие</th>
			<th class='c'>Все</th>
			<th class='c'>Группа</th>
			<th class='c'>Модераторы</th>
			<th class='c'>Никто</th>
			<th class='c'>Как в переводе</th>
		</tr></thead>
		<tbody>
		<?php
			foreach(Yii::app()->params["ac_areas_chap"] as $role => $title) {
				echo "<tr>";
				echo "<th>{$title}</th>";
				foreach(array("a", "g", "m", "o", "") as $v) {
					echo "<td class='c'>";
					if($role != "ac_read" or $v != "a") {
						echo "<input type='radio' name='Chapter[{$role}]' value='{$v}'" . ($chap->$role == $v ? " checked" : "") . ($chap->book->opts_get(Book::OPTS_BAN_COPYRIGHT) && $v == "a" ? " disabled" : "") . " />";
					}
					echo "</td>";
				}
			}
		?>
		</tbody>
		</table>
	</div>
</div>
<?php
	else:
?>
<p class="help-block">Особые права доступа можно установить только для одной главы.</p>
<?php
	endif;

	echo "<div class='form-actions' style='margin-bottom:0'>";
	echo CHtml::htmlButton(
		"<i class='icon-ok icon-white'></i> Сохранить",
		array("type" => "submit", "class" => "btn btn-primary click-wait")
	) . " ";
	if(!$chap->isNewRecord) echo CHtml::htmlButton(
		"<i class='icon-ban-circle icon-white'></i> Удалить",
		array("onclick" => "E.rm()", "class" => "btn btn-danger", "id" => "btn-remove")
	) . " ";
	echo CHtml::htmlButton(
		"Отмена",
		array("onclick" => $ajax ? "CE.cancel()" : ("location.href='" . ($chap->book->url) . "'"), "class" => "btn")
	);
	echo "</div>";

	$this->endWidget();
?>

protected/views/chapter/import_A_1.php
<?php
	/**
	 * @var TextSource $options
	 * @var Chapter $chap
	 */

	$this->pageTitle = "Импортировать текст в перевод {$chap->book->fullTitle}";

	Yii::app()->bootstrap->registerTabs();
?>
<style type="text/css">
	#TextSource_text {height:200px;}
	form.form-hide-errors .error span.help-block {display:none;}
</style>
<script type="text/javascript">
var I = {
	src_type: function(type) {
		$("#form-prepare-text [name=TextSource\\[src_type\\]]").val(type);
		return false;
	}
}
</script>
<h1>Импортировать текст</h1>
<p>
	Перевод: <?=$chap->book->ahref; ?>, <?=$chap->ahref; ?>
</p>
<?php
	if($chap->n_verses != 0) {
		echo "<div class='alert alert-block alert-warning'><strong>Внимание!</strong> В этой главе уже есть оригинальный текст. Если вы импортируете новый оригинал, старый текст будет уничтожен вместе с переводами и комментариями!</div>";
	}
?>
<!-- form method='post' id='form-prepare-text' class="form-inline" action="<?=$chap->getUrl("import"); ?>" enctype="multipart/form-data" -->
<?php
	/** @var TbActiveForm $form */
	$form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
		"id" => "form-prepare-text",
		"action" => $chap->getUrl("import"),
		"type" => "horizontal",
		"inlineErrors" => false,
		"htmlOptions" => array(
			"class" => "form-hide-errors",
			"enctype" => "multipart/form-data",
		),
	));
?>
	<input type='hidden' name='TextSource[src_type]' value='1' />

	<div class="tabbable">
		<ul class="nav nav-tabs">
			<li <?=$options->src_type == 1 ? "class='active'" : ""; ?>><a href="#1" data-toggle="tab" onclick='return I.src_type(1)'>Вставить или набрать</a></li>
			<li <?=$options->src_type == 2 ? "class='active'" : ""; ?>><a href="#2" data-toggle="tab" onclick='return I.src_type(2)'>Из файла</a></li>
<?php if(0) : // NOT IMPLEMENTED, TODO Импорт оригинала из HTML ?>
	<li <?=$options->src_type == 3 ? "class='active'" : ""; ?>><a href="#3" data-toggle="tab" onclick='return I.src_type(3)'>Из интернета</a></li>
<?php endif; ?>
		</ul>
		<div class="tab-content">
			<div id="1" class="tab-pane <?=$options->src_type == 1 ? "active" : ""; ?>">
				<div class="control-group">
					<textarea name='TextSource[text]' class='span8' id='TextSource_text'></textarea>
					<p class='help-block'>Пожалуйста, не более 500 килобайт. Тексты большего размера разбейте на отдельные главы.</p>
				</div>
			</div>
			<div id="2" class="tab-pane <?=$options->src_type == 2 ? "active" : ""; ?>">
				<?php echo $form->fileFieldRow($options, "file", array("hint" => "Пожалуйста, только файлы .TXT не тяжелее 500 килобайт. Тексты большего размера разбейте на отдельные главы.")); ?>
				<?php echo $form->dropDownListRow($options, "encoding", Yii::app()->params["encodings"]); ?>
			</div>
<?php if(0) : // NOT IMPLEMENTED, TODO Импорт оригинала из HTML ?>
			<div id="3" class="tab-pane <?=$options->src_type == 3 ? "active" : ""; ?>">
				<?php echo $form->textFieldRow($options, "url", array("placeholder" => "http://", "class" => "span7", "hint" => "Из страницы будет загружено не более 500 КБ. Если вы хотите перевести более длинную страницу, сохраните её себе на диск, откройте в браузере и скопируйте содержимое частями через буфер обмена.")); ?>
			</div>
			<?php endif; ?>
		</div>
	</div>
	<?php
		echo $form->dropDownListRow($options, "chopper", $options->choppers);
	?>

	<div class="form-actions">
		<button type="button" class="btn btn-success" onclick="location.href='<?=$chap->book->url; ?>'">
			<i class="icon-remove icon-white"></i>
			Отмена
		</button>
		<button type="submit" class="btn btn-primary pull-right">
			Далее
			<i class="icon-white icon-arrow-right"></i>
		</button>
	</div>
<?php $this->endWidget(); ?>

protected/views/chapter/import_A_2.php
<?php
	/**
	 * @var Array $text
	 * @var Chapter $chap
	 */

	$this->pageTitle = "Импортировать текст в перевод {$chap->book->fullTitle}";
?>
<style type="text/css">
	#TextSource_text {height:200px;}

	#Chopper {
		border:1px solid #777;
		padding:10px;
	}

	#Chopper p {
		border-bottom:1px dashed #777;
		margin:0px 0;
		padding:10px 0;
	}
	#Chopper p:hover {
		background:#eee;
	}
	#Chopper p.toobig {
		border-left:20px solid red;
		padding-left:20px;
	}
	#Chopper p a.glue, #Chopper p a.rm{ font-size:10px; display:none;}
	#Chopper p:hover a.glue, #Chopper p:hover a.rm{ display:inline;}

	#Chopper span:hover {
		background:#adff2f;
		border-left:2px solid black;
		padding-left:5px;
	}
</style>
<script type="text/javascript">
var C = {
	init: function() {
		$("#Chopper")
			.delegate("span", "click", C.chop)
			.delegate("a.glue", "click", C.glue)
			.delegate("a.rm", "click", C.rm);
	},
	chop: function() {
		var p = $(this).parent("p");

		var p1 = $($(this).prevAll().get().reverse());
		var p2 = $(this).nextAll().andSelf();
		if(p1.length == 0) return;
		var html1 = "", html2 = "";
		p1.each(function() {
			html1 += $(this).outerHTML();
		});
		p2.each(function() {
			html2 += $(this).outerHTML();
		});

		p.replaceWith("<p>" + html1 + " <a href='#' class='glue'>(склеить)</a> <a href='#' class='rm'>(удалить)</a></p><p>" + html2 + "</p>");
		C.check_lengths();
	},
	glue: function(e) {
		e.preventDefault();

		var p1 = $(this).parent("p");
		var p2 = p1.next("p");
		if(p2.length == 0) return false;
		p1.append(p2.html());
		$(this).remove();
		p2.remove();

		console.log("new length: %d", p1.text().length);
		if(p1.text().length > 1024) p1.addClass("toobig");

		return false;
	},
	rm: function(e) {
		e.preventDefault();
		$(this).parent("p").remove();
	},
	save: function() {
		var i = 0, $form = $("#form-chop-text");
		$form.find("button.save").attr("disabled", true);
		$("#Chopper p").each(function() {
			var $this = $(this);
			$this.children("a").remove();
			$("<input type='hidden' />").val($this.text()).attr("name", "t[txt][" + i + "]").appendTo($form);
			i++;
		});
		$("#form-chop-text").submit();
//		$("<input type='submit'>").appendTo("#form-chop-text");
	},
	check_lengths: function() {
		$("#Chopper p").each(function() {
			var $p = $(this);
			if($p.text().length > 1024) $p.addClass("toobig");
			else $p.removeClass("toobig");
		})
	}
}
$(C.init);
</script>
<h1>Импортировать текст</h1>
<p>
	Перевод: <?=$chap->book->ahref; ?>, <?=$chap->ahref; ?>
</p>

<p class="help-block">
	Кликами мыши разбейте текст на удобные для перевода фрагменты. Имейте в виду, что одна глава не может содержать более 4000 фрагментов.
</p>

<form method='post' id='form-chop-text' action="<?=$chap->getUrl("import_text_save"); ?>">
<div id="Chopper">
<?php
	foreach($text as $p) {
		if(trim($p) == "") continue;
		$class = "";
		if(mb_strlen($p) > 1024) $class = " class='toobig'";
		$p = htmlspecialchars($p);

		$p = "<span>" . preg_replace('/(\s+)/', '\1</span><span>', $p . "\n") . "</span>";

		echo "<p{$class}>";
		echo nl2br($p);
		echo "<a href='#' class='glue'>(склеить)</a> ";
		echo "<a href='#' class='rm'>(удалить)</a> ";
		echo "</p>";
	}
?>
</div>

<div class="form-actions">
	<button type="button" class="btn btn-success cancel" onclick="location.href='<?=$chap->getUrl("import"); ?>'">
		<i class="icon-arrow-left icon-white"></i>
		Назад
	</button>
	<button type="button" class="btn btn-primary pull-right save" onclick="C.save()">
		Сохранить
		<i class="icon-arrow-right icon-white"></i>
	</button>
</div>
</form>

protected/views/chapter/import_S.php
<?php
	/**
	 * @var ImportSubsForm $options
	 * @var Chapter $chap
	 */

	$this->pageTitle = "Импортировать субтитры";
?>
<style type="text/css">
form.form-hide-errors .error span.help-block {display:none;}
</style>
<h1>Импортировать субтитры</h1>
<p>
	Перевод: <?=$chap->ahref; ?>
</p>
<?php
	if($chap->n_verses != 0) {
		echo "<div class='alert alert-block alert-warning'><strong>Внимание!</strong> В этой главе уже есть оригинальный текст. Если вы импортируете новый оригинал, старый текст будет уничтожен вместе с переводами и комментариями!</div>";
	}

	/** @var TbActiveForm $form */
	$form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
		"id" => "form-import",
		"type" => "horizontal",
		"inlineErrors" => false,
		"action" => $chap->getUrl("import_subs"),
		"htmlOptions" => array(
			"class" => "form-hide-errors",
			"enctype" => "multipart/form-data",
		),
	));

	echo $form->errorSummary($options);

	echo $form->fileFieldRow($options, "src", array("hint" => "Не более 1 мегабайта, пожалуйста"));
	echo $form->dropDownListRow($options, "format", array("srt" => "SRT"));
	echo $form->dropDownListRow($options, "encoding", Yii::app()->params["encodings"]);
?>
<div class="form-actions">
	<button type="submit" class="btn btn-primary">
		<i class="icon-ok icon-white"></i>
		Импортировать
	</button>
	<button type="button" class="btn btn-success" onclick="location.href='<?=$chap->book->url; ?>'">
		<i class="icon-remove icon-white"></i>
		Отмена
	</button>
</div>
<?php
	$this->endWidget();
?>

protected/views/chapter/orig.php
<?php
	/**
	 * @var Chapter $chap
	 * @var GenOptions $options
	 */
	$this->pageTitle = "Скачать оригинальные субтитры {$chap->book->fullTitle}: {$chap->title}";
?>
<h1>Скачать оригинальные субтитры <?php echo "{$chap->book->s_title}: {$chap->title}"; ?></h1>

<form method="get" action="<?=$chap->getUrl("orig_download"); ?>" class="form-horizontal">
	<div class="control-group">
		<label class="control-label">Формат:</label>
		<div class="controls">
			<select name="format">
				<?php
				foreach(GenOptions::$format_options[$chap->book->typ] as $k => $v) {
					echo "<option value='{$k}'" . ($k == $options->format ? " selected" : "") . ">{$v}</option>";
				}
				?>
			</select>
		</div>
	</div>
	<div class="control-group">
		<label class="control-label">Кодировка:</label>
		<div class="controls">
			<select name="enc">
				<?php
				foreach(Yii::app()->params["encodings"] as $k => $v) {
					echo "<option value='{$k}'" . ($k == $options->enc ? " selected" : "") . ">{$v}</option>";
				}
				?>
			</select>
		</div>
	</div>
	<div class="control-group">
		<label class="control-label">Перенос строки:</label>
		<div class="controls">
			<select name="crlf">
				<?php
				foreach(GenOptions::$crlf_options as $k => $v) {
					echo "<option value='{$k}'" . ($k == $options->crlf ? " selected" : "") . ">{$v}</option>";
				}
				?>
			</select>
		</div>
	</div>

	<div class="form-actions">
		<button type="submit" class="btn btn-primary">
			<i class="icon-download-alt icon-white"></i> Скачать
		</button>
		<a href="<?=$chap->book->url; ?>" class="btn">К оглавлению</a>
		<a href="<?=$chap->url; ?>" class="btn">Перевод этой главы</a>
	</div>

</form>

protected/views/chapter/ready_empty.php
<?php
/**
 * @var Chapter $chap
 */
?>
<h1>Скачать перевод <?php echo "{$chap->book->fullTitle}: {$chap->title}"; ?></h1>
<p>
	В этой главе нет ни одного переведённого фрагмента.
</p>
<p>
	<a href="<?=$chap->book->url; ?>">К оглавлению</a> |
	<?php if($chap->can("tr")) echo "<a href='{$chap->url}'>Перевести</a>"; ?>
</p>